### PR TITLE
Adds support for Laravel 9

### PR DESCRIPTION
**Pull request by tabacitu**
Hey @mewebstudio ,

Laravel 9 is just around the corner (due in 5 days). I thought we'd get ahead of this thing, and provide support before it's out. Tested this package against L9 and... what do you know, everything still works great 🎉  So it only needs a dependency version bump to support L9. That's what this PR does.

Again, thanks for a great package.
Cheers!

PS. My only concern in terms of breaking changes was [this one](https://laravel.com/docs/master/upgrade#custom-casts-and-null) but it seems it's all fine, `clean(null)` works jus as well as `clean('')`. So we're good 💪

### CODE REVIEW

**Comment by HDVinnie** [comment]
Can please merge this?

**Comment by tariqulislamrc** [comment]
We need urgent support for laravel v9. Please merge this or release a laravel v9 compatible version ASAP.

**Comment by DennisHalili** [comment]
We are hoping to merge this PR #158 
Since Laravel 9 is LTS.
Thank you!

**Comment by HDVinnie** [comment]
> We are hoping to merge this PR #158
> Since Laravel 9 is LTS.
> Thank you!

Its actually not LTS

https://laravel.com/docs/9.x/releases#laravel-9
https://twitter.com/taylorotwell/status/1491834866295525389

**Comment by publiux** [comment]
Pinging @mewebstudio . This is a show stopper for L9 upgrades for many.

**Pull request merged**
