### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by Xiphin**
Fix: https://github.com/ezyang/htmlpurifier/pull/137

### CODE REVIEW

**Comment by marcintabaka** [comment]
+1

**Comment by timacdonald** [comment]
+1 on this.

Also: https://github.com/mewebstudio/Purifier/issues/59

**Comment by tortuetorche** [comment]
Hi @mewebstudio,

Can you merge this pull-request please?

Have a good day,
Tortue Torche

**Comment by mewebstudio** [comment]
Merged, thank you.

**Pull request merged**
