### PR TITLE
Cleaning and refactoring for good tests

### PR DESCRIPTION
**Pull request by ptondereau**
Hello,

I've make a "big" refactor in order to propose you reals tests.
A MakeFile is no longer required ;)

### CODE REVIEW

**Comment by Malezha** [comment]
Purifier release 4.8.0, so can u update pull request?
If maintainer is gone maybe u create fork?

**Comment by ptondereau** [comment]
@Malezha should be ok now

**Comment by stayallive** [comment]
@ptondereau ~~maybe also nice to remove PHP <=5.5 support since http://php.net/supported-versions.php~~ nvm, this is for L5 support ofcourse 👍 

Also the fork idea is not bad, came here to do the same but then saw your great work. I would applaude a good fork with tests and updated purifier release!

**Comment by ptondereau** [comment]
@stayallive There are tons of Laravel's Purifier on packagist, you could use my fork but I'm not sure about to create a new repo...

Give a 👍 on this comment if you want so.

**Comment by stayallive** [comment]
Yeah you are probably right, I can see 4 already by searching on "laravel purifier" would be nice to get some input from @mewebstudio on what thet state of this package is. And if it's abanded mark it so and fork it to elsewhere or transfer/add ownership or something.

**Comment by Malezha** [comment]
Of course, I proposed make fork only if absence of support from the @mewebstudio. This request already month without any response and I thought he a bit of abandoned =)

**Comment by Malezha** [comment]
@mewebstudio can you create new release tag for this update?

**Pull request merged**
