### PR TITLE
Update require to support Laravel 5.5

### PR DESCRIPTION
**Pull request by JellyBool**
Update require to support Laravel 5.5

### CODE REVIEW

**Comment by markeilander** [comment]
Can someone rebuild this pull request?

**Comment by JellyBool** [comment]
@markeilander Ha, I don't know why it's failing.

**Comment by markeilander** [comment]
The command "vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover" exited with 1.

I think laravel 5.5 requires php 7.1....

**Comment by markeilander** [comment]
One unit test is failing...

There was 1 failure:
1) Mews\Tests\Purifier\PurifierTest::testGetConfigMetthod
Failed asserting that Array &0 (
    'Core.Encoding' => 'UTF-8'
    'Cache.SerializerPath' => '/home/travis/build/mewebstudio/Purifier/vendor/orchestra/testbench-core/src/Traits/../../fixture/storage/app/purifier'
    'Cache.SerializerPermissions' => 493
    'HTML.Doctype' => 'HTML 4.01 Transitional'
    'HTML.Allowed' => 'div,b,strong,i,em,u,a[href|title],ul,ol,li,p[style],br,span[style],img[width|height|alt|src]'
    'CSS.AllowedProperties' => 'font,font-size,font-weight,font-style,font-family,text-decoration,padding-left,color,background-color,text-align'
    'AutoFormat.AutoParagraph' => true
    'AutoFormat.RemoveEmpty' => true
) is identical to Array &0 (
    'Core.Encoding' => 'UTF-8'
    'Cache.SerializerPath' => '/home/travis/build/mewebstudio/Purifier/vendor/orchestra/testbench-core/src/Traits/../../fixture/storage/app/purifier'
    'Cache.SerializerPermissions' => 493
    'HTML.Doctype' => 'XHTML 1.0 Strict'
    'HTML.Allowed' => 'div,b,strong,i,em,a[href|title],ul,ol,li,p[style],br,span[style],img[width|height|alt|src]'
    'CSS.AllowedProperties' => 'font,font-size,font-weight,font-style,font-family,text-decoration,padding-left,color,background-color,text-align'
    'AutoFormat.AutoParagraph' => true
    'AutoFormat.RemoveEmpty' => true
).
/home/travis/build/mewebstudio/Purifier/tests/PurifierTest.php:50
FAILURES!
Tests: 13, Assertions: 17, Failures: 1.

**Comment by markeilander** [comment]
Either way, it should be accepted....

**Pull request merged**
