### PR TITLE
Fix custom definitions

### PR DESCRIPTION
**Pull request by zarianec**
It looks like HTMLPurifier_Config::inherit($config) that used when creating purifier instance, doesn't use custom definitions from parent config object.

I changed it to use config object directly.

### CODE REVIEW

**Comment by zarianec** [comment]
I found it isn't work as expected

**Comment by bhuvidya** [comment]
So you don't have any more clues? What you did looks right when comparing with other code such as https://github.com/kennberg/php-htmlpurfier-html5 - so it's baffling.

I really need HTML5 support, it's so frustrating.

**Comment by bhuvidya** [comment]
I have had a quick go at using https://github.com/xemlock/htmlpurifier-html5 and so far it works. It might be worth having a look at this code to see if it has any clues.

**Comment by zarianec** [comment]
I will have a closer look on it this weekend.

**Comment by zarianec** [comment]
@bhuvidya See this one please #82

**Pull request closed without merging**
