### PR TITLE
update illuminate to laravel 6

### PR DESCRIPTION
**Pull request by wa7eedem**
add support for laravel 6

### CODE REVIEW

**Comment by illuminatusds** [comment]
php version would also need bumping to at least 7.2, as this is the min requirement for laravel 6

**Comment by gl3nda85** [comment]
can we please get this merged

**Comment by wa7eedem** [comment]
if I set the php to 7.2 : 
- should i remove the support for old versions : 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* || 5.6.* || 5.7.* || 5.8.* 
- won't that will brake the package for old versions ?

also I don't know way travis is failing I added the php 7.2 !

**Comment by gl3nda85** [comment]
does 5.8 support 7.2? we have been using 7.2 for a while now

**Comment by gl3nda85** [comment]
image

7.2 seems to be succeeding

**Comment by wa7eedem** [comment]
yes we also using laravel 5.8 with php 7.3.2 and its working , but i'm worrying about older versions of php , the package will stop working for them .

I think its better to publish this on a separate branch .

**Comment by gl3nda85** [comment]
maybe do version 3

**Pull request merged**
