### PR TITLE
add laravel 10 support

### PR DESCRIPTION
**Pull request by pxpm**

### CODE REVIEW

**Comment by txdFabio** [comment]
same issue, please do the merge

**Comment by Iandancun** [comment]
Please merge this PR, we are upgrading to Laravel 10

**Comment by txdFabio** [comment]
I've done another PR to fix a version constraint error: https://github.com/mewebstudio/Purifier/pull/186

**Comment by pxpm** [comment]
I've merged @txdFabio changes here since I need to use this branch too 👍 

Cheers

**Pull request closed without merging**
