### PR TITLE
Fix custom definitions and custom elements

### PR DESCRIPTION
**Pull request by zarianec**
I removed call of `HTMLPurifier_Config::inherit()` because inherited config object doen't use custom definitions from parent one.

Also creating of config object for purifier was heavilly refactored. All related stuff moved to separate class.
Another problem is that HTMLPurifier library ignore any custom elements if `HTML.Allowed` or `HTML.AllowedElements` provided in config. So we need to duplicate each custom element name in this properties. I made this to be done automatically. So now if there is a custom elements defined in cofig - they will be appended to the list of `HTML.Allowed` or `HTML.AllowedElements` depending of which is provided.

Also creating of config object moved to `clean()` method if custom config provided. This makes posible to use custom elements even with dynamic configuration.

Fixed old tests and added some new ones.

Please review and let me know if something must be fixed.

P.S. Sorry for my english, I'm just studying it.

### CODE REVIEW

**Comment by bhuvidya** [comment]
Hi @zarianec . Thanks so much for doing all this work. I pulled your new work from your forked repo, and tested it, and it works, but only if I comment out the `HTML.Allowed` entry in the `purifier.settings.default` array. I even created new settings blocks, analogous to `defaults`, and they worked until I added in a `HTML.Allowed` entry. Once I comment this out, all the HTML5 custom definitions/elements/attributes work, and work exactly as I specify them. I haven't had time to burrow into the code to find out why but just thought I would point this out. 

Now, it doesn't seem to matter that `HTML.Allowed` is commented out - the purifier will still accept all the elements in that entry anyway. Weird huh?

But I am very happy, because I can still do all the custom purifying I need to from your new work.

Thanks!

**Comment by zarianec** [comment]
@bhuvidya I am pretty shure it's a cache. Try to remove <your project root>/storage/app/purifier folder and try it.

**Comment by bhuvidya** [comment]
Hi @zarianec - I tried deleting the cache but that didn't seem to fix it. For example, with `HTML.Allowed` uncommented, and cache deleted, I get the following in `tinker`:

```
>>> clean('<a href="/about" target="_blank">about</a>')
=> "<a href="/about">about</a>"
```

But when I comment out the `HTML.Allowed` line, and delete cache again, I get:

```
>>> clean('<a href="/about" target="_blank">about</a>')
=> "<a href="/about" target="_blank" rel="noreferrer noopener">about</a>"
```

Weird huh?

**Comment by zarianec** [comment]
Ah, I've got it. Now I'm starting to think that using `HTML.Allowed` together with custom definitions is not a good idea at all.

@bhuvidya - in your example it works just like it must be. In `HTML.Allowed` section we have a rule `a[href|title]` - so only href and title are allowed. Custom attributes in the config doesn't override definitions in the `HTML.Allowed`. And if you will add `target` to list of allowed types (a[href|title|target]), you will get exact the same result as if you comment `HTML.Allowed`. And to be sure that custom attributes works, You can try to do something like:

```
>>> clean('<a href="/about" target="_forbidden">about</a>')
=> "<a href="/about">about</a>"
```

For now I just made the custom elements to be appended to the list of `HTML.Allowed`. For example HTML5 `section` tag from custom definitions will be added to the allowed list like `...,img[width|height|alt|src],section`. This means that now we can use this tag in dirty html but all the attributes will be cut off.

```
>>> clean('<section class="some-class">Hello World!</section>')
=> "<section>Hello World!</section>"
```

I don't have any ideas how to deal with this except of manually add this tags to `HTML.Allowed` or to remove (comment) `HTML.Allowed` at all.

**Comment by zarianec** [comment]
I thought little bit about the HTML Purifier custom definitions and now I'm sure that appending custom elements to the list of allowed elements - is a very bad approach and was my mistake.
I'm going to remove this from the pull-request and to leave the end-users to decide which elements and attributes to be allowed.

**Comment by bhuvidya** [comment]
@zarianec Thanks for that info and research. Works pretty good for me when I do the hack of commenting out the `HTML.Allowed` field, so I forked your fork and I'm going to stick with it for now. Cheers.

**Pull request merged**
