### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by jifunks**
Laravel 5.7 compatibility

### CODE REVIEW

**Comment by stayallive** [comment]
Laravel 5.7 was tagged today, so it would be great if this could be tagged and released 👍

**Comment by sebastiaanluca** [comment]
Waiting for this to get merged :)

**Comment by luozhenyu** [comment]
Also look forward to it. I can't upgrade to Laravel 5.7 because of confliction with this package.

**Comment by sebastiaanluca** [comment]
Currently using this fork/PR until it gets updated. Since all other issues have been open for quite a while, some even without response, I doubt this will get resolved soon —no pressure though ;).

```
"require": {
    "mews/purifier": "dev-patch-1",
},
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/jifunks/Purifier.git"
    }
],
```

**Comment by forxer** [comment]
please @mewebstudio can you merge this and release it ?

**Comment by cron13** [comment]
damn

**Comment by EtoileFilante** [comment]
I've emailed mewebstudio, hopefully we can get that merge soon

**Pull request merged**
