### PR TITLE
laravel-10 support and fix required version format

### PR DESCRIPTION
**Pull request by txdFabio**
fixed compose require version format and addedd laravel-10 support

### CODE REVIEW

**Review by ali-alharthi — CHANGES_REQUESTED** [review]
phpunit should also include 10:
`"phpunit/phpunit": "^8.0|^9.0|^10",`

**Comment by txdFabio** [comment]
> phpunit should also include 10: `"phpunit/phpunit": "^8.0|^9.0|^10",`

done!

**Comment by faytekin** [comment]
@mewebstudio ping

**Comment by fabiofdsantos** [comment]
ping @mewebstudio

**Comment by tabacitu** [comment]
Thanks for the PR @txdFabio 🙏 With your PR, `Purifier::clean()` function works just as fine in our L10 tests!

@mewebstudio when can we expect a merge & tag?

**Comment by kminek** [comment]
@mewebstudio are you okay? i noticed that you're from Turkey and there were some serious earthquakes there...

**Comment by faytekin** [comment]
> @mewebstudio are you okay? i noticed that you're from Turkey and there were some serious earthquakes there...

I don't think the person is living in the affected area of the earthquake. If they didn't go to that area during the earthquake, they shouldn't have been affected.

**Comment by pxpm** [comment]
> > @mewebstudio are you okay? i noticed that you're from Turkey and there were some serious earthquakes there...
> 
> I don't think the person is living in the affected area of the earthquake. If they didn't go to that area during the earthquake, they shouldn't have been affected.

I think that's a very rude way of putting up the issue. People have family, friends and empathy with other human beings. 

There are many ways to get affected by the events, even if living in another country. 

I make @kminek my words, and hope @mewebstudio , his relatives and friends are all ok 🙏 

Also I am here with all other developers in the hopes that we can help @mewebstudio to merge this PR 👍 

Cheers

**Comment by ali-alharthi** [comment]
If you're in a hurry, you can always find other packages or fork this one. For example the following [stevebauman/purify](https://github.com/stevebauman/purify).
Good luck.

**Review by myMartek — APPROVED** [review]

**Comment by txdFabio** [comment]
I've seen you have merged the PR, thanks.
Can you also tag for a new release, please?

**Pull request merged**
